version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: collaborative-bucket-list-db
    environment:
      POSTGRES_DB: collaborative_bucket_list
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d collaborative_bucket_list"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
