global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Backend application
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8080"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  # Frontend application (if exposing metrics)
  - job_name: "frontend"
    static_configs:
      - targets: ["frontend:3000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Database metrics (if using postgres_exporter)
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scrape_interval: 30s
